version: '3.9'

services:
  user_service:
    build:
      context: ./prgrinzh-main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  parcel_service:
    build:
      context: ./parcel_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/parcels
    command: ["./wait-for-it.sh", "db:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]

  delivery_service:
    build:
      context: ./delivery_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongo

  message_service:
    build:
      context: ./message_service
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8083:8083"
    environment:
      MONGO_URI: mongodb://mongo:27017

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parcels
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
